### ISSUE TITLE
Cemu application hangs or render incorrectly when using a radeon GCN > 1.2 

### ISSUE THREAD

**Issue by mikakev1** [mikakev1/mesa_mild_compatibility#2]

**Comment by Kierek** [comment]
RX 580, latest mesa_mild_compatibility, LLVM from mesa-git repo(version 321932-1), linux 4.14.12, cemu 1.8.2b, Arch Linux.

After a little bit of testing I think I've found the problematic shader.

Running Mario Kart 8 "the standard way" (DRI_PRIME=1 MESA_DEBUG=context MESA_GLSL=log MESA_GLSL_CACHE_DISABLE=true GALLIUM_HUD=fps,cpu,VRAM-usage,num-compilations,GPU-load WINEDEBUG="+opengl,+wgl" wine explorer /desktop=Cemu,2560x1440 /home/kierek/Wine/cemu/Cemu.exe) it doesn't crash, it just freezes with Cemu.exe eating 25% CPU(1 thread).

After deleting precompiled shader cache t freezes(creating this failed file), and the other time it compiles just fine with cemu crashing immediately after. I'm attaching both files.

[shader_67.zip](https://github.com/mikakev1/mesa_mild_compatibility/files/1615767/shader_67.zip)

**Comment by Kierek** [comment]
When running Mario Tennis, there's another shader failing to compile(but not everytime, I'm constantly removing compiled or precompiled shader cache). This one was made with both caches removed.

[shader_57.txt](https://github.com/mikakev1/mesa_mild_compatibility/files/1615864/shader_57.txt)
(changed from .frag to .txt)

**Comment by mikakev1** [comment]
Ok, thanks, I'm going to reformat it and feed it to the standalone glsl compiler.
Great job !

**Comment by Kierek** [comment]
Do you need more samples? I've been testing it with NIR, as you suggested in the other issue, but it crashes much faster, about 2 shaders in, complaining about "no opengl 4.0 support".

**Comment by mikakev1** [comment]
Hi, 
Considering shader57.frag
are you using bicubic filtering? If so, could you disable it (switch to bilinear).

**Comment by Kierek** [comment]
Hi,

> Considering shader57.frag
are you using bicubic filtering? If so, could you disable it (switch to bilinear).

Indeed, I was using bicubic filtering. After changing it to bilinear it compiles much further, crashing at shader_170.vert and shader_172.vert.

[shaders.zip](https://github.com/mikakev1/mesa_mild_compatibility/files/1628503/shaders.zip)

> As a general rules do not use precompiled shader cache (unless you build it yourself using mesa and your card) and use only bilinear filtering.
Did you mean transferable? I use transferable if I can, but from what I noticed it doesn't change cemu behaviour much.

**Comment by Kierek** [comment]
I've just read that RadeonSI should now expose OpenGL 4.5 support with NIR backend. Will this be of any help? If I understand correctly, it should resolve the problem with "no opengl 4.0 support" when using nir.

**Comment by mikakev1** [comment]
Best thing I can say : Test it !

**Comment by Kierek** [comment]
> Best thing I can say : Test it !

I'd love to, but I guess that I still need your fork and it doesn't include these patches, so... :D

**Comment by mikakev1** [comment]
Updated !

**Comment by Kierek** [comment]
No progress unfortunately. With NIR I'm unable to get some failed shaders, but it still crashes anyway. There's only this LLVM error happening every time.

Without NIR

> LLVM ERROR: Cannot select: 0x7f5f98134050: f16 = bitcast 0x7f5f98267658
  0x7f5f98267658: i32 = srl 0x7f5f98120ed0, Constant:i32<16>
    0x7f5f98120ed0: i32 = bswap 0x7f5f981786d8
      0x7f5f981786d8: i32 = and 0x7f5f98133968, Constant:i32<65535>
        0x7f5f98133968: i32 = extract_vector_elt 0x7f5f98133900, Constant:i32<0>
          0x7f5f98133900: v4i32 = bitcast 0x7f5f9809e598
            0x7f5f9809e598: v4f32,ch = BUFFER_LOAD_FORMAT<LD16[TargetCustom7(addrspace=2)](align=1)(dereferenceable)> 0x7f5f98177918, 0x7f5f9809a3c0, 0x7f5f9809a0e8, Constant:i32<0>, Constant:i1<0>, Constant:i1<0>
              0x7f5f9809a3c0: v4i32,ch = load<LD16[%16(addrspace=2)](dereferenceable)(invariant)> 0x7f5f98177918, 0x7f5f98099998, undef:i64
                0x7f5f98099998: i64,ch = CopyFromReg 0x7f5f98177918, Register:i64 %4
                  0x7f5f98099930: i64 = Register %4
                0x7f5f9809a358: i64 = undef
              0x7f5f9809a0e8: i32,ch = CopyFromReg 0x7f5f98177918, Register:i32 %13
                0x7f5f9809a080: i32 = Register %13
              0x7f5f9809a490: i32 = Constant<0>
              0x7f5f9809a4f8: i1 = Constant<0>
              0x7f5f9809a4f8: i1 = Constant<0>
          0x7f5f9809a490: i32 = Constant<0>
        0x7f5f982678c8: i32 = Constant<65535>
    0x7f5f9809ec18: i32 = Constant<16>
In function: main

With NIR

> LLVM ERROR: Cannot select: 0x7f0604130e50: f16 = bitcast 0x7f06042e6b90
  0x7f06042e6b90: i32 = srl 0x7f06042965f8, Constant:i32<16>
    0x7f06042965f8: i32 = bswap 0x7f0604130d80
      0x7f0604130d80: i32 = and 0x7f0604130358, Constant:i32<65535>
        0x7f0604130358: i32 = extract_vector_elt 0x7f06041302f0, Constant:i32<0>
          0x7f06041302f0: v4i32 = bitcast 0x7f060427e2e0
            0x7f060427e2e0: v4f32,ch = BUFFER_LOAD_FORMAT<LD16[TargetCustom7(addrspace=2)](align=1)(dereferenceable)> 0x7f0604010a98, 0x7f0604140c00, 0x7f0604140928, Constant:i32<0>, Constant:i1<0>, Constant:i1<0>
              0x7f0604140c00: v4i32,ch = load<LD16[%16(addrspace=2)](dereferenceable)(invariant)> 0x7f0604010a98, 0x7f06041401d8, undef:i64
                0x7f06041401d8: i64,ch = CopyFromReg 0x7f0604010a98, Register:i64 %4
                  0x7f0604140170: i64 = Register %4
                0x7f0604140b98: i64 = undef
              0x7f0604140928: i32,ch = CopyFromReg 0x7f0604010a98, Register:i32 %13
                0x7f06041408c0: i32 = Register %13
              0x7f0604140cd0: i32 = Constant<0>
              0x7f0604140d38: i1 = Constant<0>
              0x7f0604140d38: i1 = Constant<0>
          0x7f0604140cd0: i32 = Constant<0>
        0x7f0604140c68: i32 = Constant<65535>
    0x7f06043aa1f0: i32 = Constant<16>
In function: main

So, I guess that our only hope is to wait for OpenGL core profile compliant Cemu build, or Vulkan backend?

**Comment by giovannilaura** [comment]
I have compiles latest mesa 17.1 with llvm6 AND patched it with a patch that allows core profiles to allow compat i found it in winebugs or mesabug tracker, compiling latest mesa 17.1 is a bit tricky and requires to change some lines of code but with mesa 17.1 latest patched cemu works so there still is hope it works on VEGA and RX480 if someone is interested and i am feeling better i could publish the mesa code on GitHub but for now i am feling not so good if someone is interested let me know and i will try to publsh the mesa patched code to github as soon as possible

**Comment by Kierek** [comment]
@giovannilaura 

But what changes did you make which differs your fork from mikakev's one? Also, why did you use mesa 17.1 and not the latest stable one or git?

**Comment by giovannilaura** [comment]
It seems that only mesa up to 17.1.10 works i tried 17.2 various versions mesa 17.3 and 17.4 but no go although 17.1.10 with llvm6 works pretty well i managed to get botw on vega and amd graphic pac at about 22fps with cemu 11.3 triple render on my ryzen 1700x 


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: Kierek <notifications@github.com> Data: 31/01/18  11:30  (GMT+01:00) A: mikakev1/mesa_mild_compatibility <mesa_mild_compatibility@noreply.github.com> Cc: Giovanni Ongaro <giovanni.nicola@ticino.com>, Mention <mention@noreply.github.com> Oggetto: Re: [mikakev1/mesa_mild_compatibility] Cemu application hangs or
  render incorrectly when using a radeon GCN > 1.2 (#2) 
@giovannilaura
But what changes did you make which differs your fork from mikakev's one? Also, why did you use mesa 17.1 and not the latest stable one or git?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mikakev1/mesa_mild_compatibility","title":"mikakev1/mesa_mild_compatibility","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mikakev1/mesa_mild_compatibility"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Kierek in #2: @giovannilaura \r\n\r\nBut what changes did you make which differs your fork from mikakev's one? Also, why did you use mesa 17.1 and not the latest stable one or git? "}],"action":{"name":"View Issue","url":"https://github.com/mikakev1/mesa_mild_compatibility/issues/2#issuecomment-361890620"}}}

**Comment by giovannilaura** [comment]
If you understand that it must convive with installed mesa i installed it in opt and llvm6 i installed it in /usr/local/llvm64 it is relatively easy to point libgl_drivers_dir and ld_library path to this version of mesa the only little problem is redundancy


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: Kierek <notifications@github.com> Data: 31/01/18  11:30  (GMT+01:00) A: mikakev1/mesa_mild_compatibility <mesa_mild_compatibility@noreply.github.com> Cc: Giovanni Ongaro <giovanni.nicola@ticino.com>, Mention <mention@noreply.github.com> Oggetto: Re: [mikakev1/mesa_mild_compatibility] Cemu application hangs or
  render incorrectly when using a radeon GCN > 1.2 (#2) 
@giovannilaura
But what changes did you make which differs your fork from mikakev's one? Also, why did you use mesa 17.1 and not the latest stable one or git?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mikakev1/mesa_mild_compatibility","title":"mikakev1/mesa_mild_compatibility","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mikakev1/mesa_mild_compatibility"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Kierek in #2: @giovannilaura \r\n\r\nBut what changes did you make which differs your fork from mikakev's one? Also, why did you use mesa 17.1 and not the latest stable one or git? "}],"action":{"name":"View Issue","url":"https://github.com/mikakev1/mesa_mild_compatibility/issues/2#issuecomment-361890620"}}}

**Comment by Kierek** [comment]
That sounds great, I'd appreciate it if you could share the code on Github and also show how I could install mesa in /opt.

PKGBUILD would be the best, if you use/are familiar with Arch Linux.

**Comment by giovannilaura** [comment]
If you can wait i could install archlinux on a virtual machine and then investigate pkgbuild and then publish on github meanwhile i could send to jou some screenshots i have many years of experience with vm i cant do it now beause i am a little sick hope you can wait


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: Kierek <notifications@github.com> Data: 31/01/18  14:39  (GMT+01:00) A: mikakev1/mesa_mild_compatibility <mesa_mild_compatibility@noreply.github.com> Cc: Giovanni Ongaro <giovanni.nicola@ticino.com>, Mention <mention@noreply.github.com> Oggetto: Re: [mikakev1/mesa_mild_compatibility] Cemu application hangs or
  render incorrectly when using a radeon GCN > 1.2 (#2) 
That sounds great, I'd appreciate it if you could share the code on Github and also show how I could install mesa in /opt.
PKGBUILD would be the best, if you use/are familiar with Arch Linux.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mikakev1/mesa_mild_compatibility","title":"mikakev1/mesa_mild_compatibility","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mikakev1/mesa_mild_compatibility"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Kierek in #2: That sounds great, I'd appreciate it if you could share the code on Github and also show how I could install mesa in /opt.\r\n\r\nPKGBUILD would be the best, if you use/are familiar with Arch Linux."}],"action":{"name":"View Issue","url":"https://github.com/mikakev1/mesa_mild_compatibility/issues/2#issuecomment-361934659"}}}

**Comment by Kierek** [comment]
@giovannilaura 
Sure, I can wait.

@mikakev1 
What's your opinion on this? Could you publish some experimental branch with patched mesa 17.1 for me to test?

**Comment by mikakev1** [comment]
I suspect the patch Giovanni's mentionning was found on wine's bugzilla ... and it's mine to start with :)

https://bugs.winehq.org/show_bug.cgi?id=42593

**Comment by Kierek** [comment]
@mikakev1 
I've tried to apply your patch from freedesktop to 17.1.10 stable, but it fails at uniform_query.

> git apply patch.diff
error: patch failed: src/mesa/main/uniform_query.cpp:910
error: src/mesa/main/uniform_query.cpp: patch does not apply

Could you take a look?

**Comment by mikakev1** [comment]
Everything is already in there ! 
Check driconf options.

**Comment by Kierek** [comment]
I know, but your fork is based on mesa-git, and here @giovannilaura is implying that on Vega and Polaris it works only up to 17.1.10 :D

**Comment by giovannilaura** [comment]
[cemu26jun.patch.txt](https://github.com/mikakev1/mesa_mild_compatibility/files/1686578/cemu26jun.patch.txt)
here the correct patch apply it to mesa 1.7.10 git and be sure to use llvm6
will baqck soon

**Comment by giovannilaura** [comment]
here the correct patch
[cemu26jun.patch.txt](https://github.com/mikakev1/mesa_mild_compatibility/files/1686586/cemu26jun.patch.txt)
apply to mesa 17.1.10 and use llvm6
will be back later

**Comment by giovannilaura** [comment]
it also need driconf with enable glsl estensions to marm and MESA_GL_VERSION_OVERRIDE=4.5COMPAT

**Comment by giovannilaura** [comment]
sorry force GLSL extensions to warn

**Comment by giovannilaura** [comment]
sorry but i was feeling sick so the patch with all required modifications is here and the previus posts contained the patch i found on internet
[0001-CEMU-OK.patch.txt](https://github.com/mikakev1/mesa_mild_compatibility/files/1686628/0001-CEMU-OK.patch.txt)
apply to mesa 17.1.10 i used git but from some months ago)
set force_GLSL_extensions_to_warn on driconf
prefix wine call with MESA_GL_VERSION_OVERRIDE="4.5COMPAT"
for me it works

**Comment by Kierek** [comment]
It doesn't compile with llvm7(svn) and I'm not sure where I can find llvm6. I will look into this some time during the weekend.

**Comment by JohnnyonFlame** [comment]
The LLVM Error reported has been fixed in the upstream llvm repo as of revision r323932, http://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20180129/521298.html

That gets me farther, but the entire game is pitch black save for skyboxes, particle effects and some overbright textures.

https://cdn.discordapp.com/attachments/292706660877860865/408801161508945921/unknown.png

**Comment by Kierek** [comment]
@JohnnyonFlame 

You achieved this result with latest mesa-mild-compatibility and llvm-svn, right? What GPU do you have?

**Comment by giovannilaura** [comment]
I tested it on vega 64 and rx480 by using rendering offload with xrandt


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: Kierek <notifications@github.com> Data: 02/02/18  11:02  (GMT+01:00) A: mikakev1/mesa_mild_compatibility <mesa_mild_compatibility@noreply.github.com> Cc: Giovanni Ongaro <giovanni.nicola@ticino.com>, Mention <mention@noreply.github.com> Oggetto: Re: [mikakev1/mesa_mild_compatibility] Cemu application hangs or
  render incorrectly when using a radeon GCN > 1.2 (#2) 
@JohnnyonFlame
You achieved this result with latest mesa-mild-compatibility and llvm-svn, right? What GPU do you have?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mikakev1/mesa_mild_compatibility","title":"mikakev1/mesa_mild_compatibility","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mikakev1/mesa_mild_compatibility"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Kierek in #2: @JohnnyonFlame \r\n\r\nYou achieved this result with latest mesa-mild-compatibility and llvm-svn, right? What GPU do you have?"}],"action":{"name":"View Issue","url":"https://github.com/mikakev1/mesa_mild_compatibility/issues/2#issuecomment-362541696"}}}

**Comment by giovannilaura** [comment]
Be sure to driconf default glsl extensions to warn and run cemu in window also wich game you are talking?


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: João Henrique <notifications@github.com> Data: 02/02/18  09:19  (GMT+01:00) A: mikakev1/mesa_mild_compatibility <mesa_mild_compatibility@noreply.github.com> Cc: Giovanni Ongaro <giovanni.nicola@ticino.com>, Mention <mention@noreply.github.com> Oggetto: Re: [mikakev1/mesa_mild_compatibility] Cemu application hangs or
  render incorrectly when using a radeon GCN > 1.2 (#2) 
The LLVM Error reported has been fixed in the upstream llvm repo as of revision r323932, http://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20180129/521298.html
That gets me farther, but the entire game is pitch black save for skyboxes, particle effects and some overbright textures.
https://cdn.discordapp.com/attachments/292706660877860865/408801161508945921/unknown.png

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mikakev1/mesa_mild_compatibility","title":"mikakev1/mesa_mild_compatibility","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mikakev1/mesa_mild_compatibility"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JohnnyonFlame in #2: The LLVM Error reported has been fixed in the upstream llvm repo as of revision r323932, http://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20180129/521298.html\r\n\r\nThat gets me farther, but the entire game is pitch black save for skyboxes, particle effects and some overbright textures.\r\n\r\nhttps://cdn.discordapp.com/attachments/292706660877860865/408801161508945921/unknown.png"}],"action":{"name":"View Issue","url":"https://github.com/mikakev1/mesa_mild_compatibility/issues/2#issuecomment-362517028"}}}

**Comment by JohnnyonFlame** [comment]
@giovannilaura Yeah, I set that up, and also did --enable-texture-float, didn't help. The only game I'm testing is botw right now, might end up testing Bayonetta 2 if my cc balance helps.

@Kierek RX480, this result is the same for latest mesa_mild, the 17.3 branch and the patched 17.1.10 mesa. Tested with llvm-6 and llvm-svn. Didn't test 3.9 and 5 yet, but I doubt it'll be any different other than getting a bitcast LLVM Error.

**Comment by mikakev1** [comment]
Did you forget to edit the file Cemu.exe to force a #version 450?

**Comment by JohnnyonFlame** [comment]
I did #version 420 to #version 450 as was instructed.

**Comment by giovannilaura** [comment]
And it doesnt work?


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: João Henrique <notifications@github.com> Data: 02/02/18  16:42  (GMT+01:00) A: mikakev1/mesa_mild_compatibility <mesa_mild_compatibility@noreply.github.com> Cc: Giovanni Ongaro <giovanni.nicola@ticino.com>, Mention <mention@noreply.github.com> Oggetto: Re: [mikakev1/mesa_mild_compatibility] Cemu application hangs or
  render incorrectly when using a radeon GCN > 1.2 (#2) 
I did #version 420 to #version 450 as was instructed.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mikakev1/mesa_mild_compatibility","title":"mikakev1/mesa_mild_compatibility","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mikakev1/mesa_mild_compatibility"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JohnnyonFlame in #2: I did #version 420 to #version 450 as was instructed."}],"action":{"name":"View Issue","url":"https://github.com/mikakev1/mesa_mild_compatibility/issues/2#issuecomment-362607471"}}}

**Comment by giovannilaura** [comment]
Wich game?


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: João Henrique <notifications@github.com> Data: 02/02/18  16:42  (GMT+01:00) A: mikakev1/mesa_mild_compatibility <mesa_mild_compatibility@noreply.github.com> Cc: Giovanni Ongaro <giovanni.nicola@ticino.com>, Mention <mention@noreply.github.com> Oggetto: Re: [mikakev1/mesa_mild_compatibility] Cemu application hangs or
  render incorrectly when using a radeon GCN > 1.2 (#2) 
I did #version 420 to #version 450 as was instructed.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mikakev1/mesa_mild_compatibility","title":"mikakev1/mesa_mild_compatibility","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mikakev1/mesa_mild_compatibility"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JohnnyonFlame in #2: I did #version 420 to #version 450 as was instructed."}],"action":{"name":"View Issue","url":"https://github.com/mikakev1/mesa_mild_compatibility/issues/2#issuecomment-362607471"}}}

**Comment by giovannilaura** [comment]
With botw on mesa you have to enable graphicpack amd fix on vega


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: João Henrique <notifications@github.com> Data: 02/02/18  16:44  (GMT+01:00) A: mikakev1/mesa_mild_compatibility <mesa_mild_compatibility@noreply.github.com> Cc: Giovanni Ongaro <giovanni.nicola@ticino.com>, Mention <mention@noreply.github.com> Oggetto: Re: [mikakev1/mesa_mild_compatibility] Cemu application hangs or
  render incorrectly when using a radeon GCN > 1.2 (#2) 
@giovannilaura Yeah, I set that up, and also did --enable-texture-float, didn't help. The only game I'm testing is botw right now, might end up testing Bayonetta 2 if my cc balance helps.
@Kierek RX480, this result is the same for latest mesa_mild, the 17.3 branch and the patched 17.1.10 mesa. Tested with llvm-6 and llvm-svn. Didn't test 3.9 and 5 yet, but I doubt it'll be any different other than getting a bitcast LLVM Error.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mikakev1/mesa_mild_compatibility","title":"mikakev1/mesa_mild_compatibility","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mikakev1/mesa_mild_compatibility"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JohnnyonFlame in #2: @giovannilaura Yeah, I set that up, and also did --enable-texture-float, didn't help. The only game I'm testing is botw right now, might end up testing Bayonetta 2 if my cc balance helps.\r\n\r\n@Kierek RX480, this result is the same for latest mesa_mild, the 17.3 branch and the patched 17.1.10 mesa. Tested with llvm-6 and llvm-svn. Didn't test 3.9 and 5 yet, but I doubt it'll be any different other than getting a bitcast LLVM Error.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/mikakev1/mesa_mild_compatibility/issues/2#issuecomment-362604011"}}}

**Comment by oscarbg** [comment]
Guys I have Cemu running on Vega fixing issue "Cemu 1.11.1 doesn't run on Vega #1" by using up to date LLVM 7..

**Comment by Kierek** [comment]
@oscarbg 
Mesa mild or mainline? If mainline, is it 18-rc or git? Does it render correctly?

**Comment by oscarbg** [comment]
mesa mild master a few days ago.. llvm 7 prebuilt from https://apt.llvm.org/ ..

**Comment by mikakev1** [comment]
@oscarbg 
Hi, could you post an image?

We should have multiple reports.

**Comment by oscarbg** [comment]
@mikakev1 yes but left me some days.. deleted mesa mild buid due to SSD space constraints.. :-(

**Comment by Kierek** [comment]
@mikakev1 
I wanted to test it, but mesa mild stopped compiling with latest llvm-svn(325306).

**Comment by mikakev1** [comment]
ok, I pushed an update from upstream.
Seems to build fine at least on 4.15 kernel

**Comment by Kierek** [comment]
So it was a llvm bug after all! It works great :D
![zrzut ekranu z 2018-02-16 19-46-51](https://user-images.githubusercontent.com/4080084/36323792-6ab0dec0-1352-11e8-8a74-77ea749bbe13.png)

Now I have a problem with Gnome not starting with mesa mild, I have to reinstall it every boot if I want to have DE, any ideas?

@giovannilaura 
You suggested installing mesa mild in /opt and then linking to it when lauching cemu, could you share how to do it?

**Comment by mikakev1** [comment]
I'm closing the issue.
You could start a blank session with only xterm and start gnome manually, maybe you'll find a related error message. Check ~/.xinitrc

**Comment by giovannilaura** [comment]
Thete is a comprehensive tutorial how to install mesa on /opt on gamingonlinux


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: Kierek <notifications@github.com> Data: 16/02/18  19:51  (GMT+01:00) A: mikakev1/mesa_mild_compatibility <mesa_mild_compatibility@noreply.github.com> Cc: Giovanni Ongaro <giovanni.nicola@ticino.com>, Mention <mention@noreply.github.com> Oggetto: Re: [mikakev1/mesa_mild_compatibility] Cemu application hangs or
  render incorrectly when using a radeon GCN > 1.2 (#2) 
So it was a llvm bug after all! It works great :D


Now I have a problem with Gnome not starting with mesa mild, I have to reinstall it every boot if I want to have DE, any ideas?
@giovannilaura

You suggested installing mesa mild in /opt and then linking to it when lauching cemu, could you share how to do it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mikakev1/mesa_mild_compatibility","title":"mikakev1/mesa_mild_compatibility","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mikakev1/mesa_mild_compatibility"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Kierek in #2: So it was a llvm bug after all! It works great :D\r\n![zrzut ekranu z 2018-02-16 19-46-51](https://user-images.githubusercontent.com/4080084/36323792-6ab0dec0-1352-11e8-8a74-77ea749bbe13.png)\r\n\r\nNow I have a problem with Gnome not starting with mesa mild, I have to reinstall it every boot if I want to have DE, any ideas?\r\n\r\n@giovannilaura \r\nYou suggested installing mesa mild in /opt and then linking to it when lauching cemu, could you share how to do it?"}],"action":{"name":"View Issue","url":"https://github.com/mikakev1/mesa_mild_compatibility/issues/2#issuecomment-366325361"}}}

**Comment by ibrokemypie** [comment]
Still doesnt work for me, vega 56, mesa mild built today with llvm 7, running cemu works, opening mario kart 8 however causes the whole system to crash because of a gpu hang, spamming dmesg with vmc page faults

**Comment by TheYoshiGuy** [comment]
I'm having the same issue as @ibrokemypie 

Vega64 here, just built the latest mesa_mild with llvm7.
I can play BOTW and a few other games, but upon opening Mario Kart 8 version 64 with the DLC, my entire system freezes once the title screen is hit, and I have to either hit the reset key, or REISUB. No other way to recover from it.  Any ssh connections into my machine terminate, the GALLIUM_HUD freezes, etc.

My Mario Kart 8 copy is fine, it plays perfectly on my wife's computer in cemu with a nvidia graphics card.

I've tried the last 5 cemu versions, different kernels, etc but can't get it to behave any differently.

This is both using your MesaMildInstaller (docker) version and just running it without docker, installing mesa_mild to ~/mesa_mild.

**Comment by mikakev1** [comment]
If using MildInstaller it means, provided you have an up to date kernel/firmware, that the issue is elsewhere (llvm/libdrm/kernel/hw support).
You may want to wait until kernel 4.17 brings some fixes.
